version: '2'
services:
  wordpress:
    build: ./docker
    env_file: ./docker/.env
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    links:
      - mysql
  mysql:
    image: mariadb:10.1.17
    ports:
      - 8081:3306
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_DATABASE: wp
